### ISSUE TITLE
Neptune stone brick stairs have wrong texture

### ISSUE THREAD

**Issue by Breadabix** [MJRLegends/ExtraPlanets#104]
The neptune stone brick stairs have the texture of a zinc block. I have tried several things, including using a texture pack and changing the texture in the mod itself. Nothing has fixed the texture issue.

Using version 1.6.6 for 1.7.10

I dont know what else could be done to fix this issue. I am not a mod creator, coder or texture creator, so I dont know much to do with this type of issue.

**Comment by MJRLegends** [comment]
Please use latest version of my addon (v1.7.3) and report back here if you still get the issue

**Comment by Breadabix** [comment]
I cant use the latest version as it is in a modpack with 270 mods. I have tried using the latest version and I get dimensionID conflicts, planet biomes generating in the overworld and several other minor issues compared to those 2.

**Comment by MJRLegends** [comment]
@Breadabix I dont support older version, have you tried using latest version and deleting the config file so it regenerates. If not all dimension ids and biome ids can be changed via my config

**Comment by Breadabix** [comment]
I have tried this, and I got the issues above. This is the latest version I can use without major issues with the modpack. I guess 1 texture will have to stay messed up. Thanks anyways

**Comment by MJRLegends** [comment]
@Breadabix yeah i cant help you because all the issues your going to find in the version your using is fixed in the latest few so its a issue that isnt fixable by me, you i bet you could get it to work but at the cost of changing a bit of config stuff

**Comment by Breadabix** [comment]
I have updated to the latest 1.7.10 version and still have this issue, both with sphax and the vanilla textures.

**Comment by Breadabix** [comment]
I think the issue is the default recipe, the stone brick stairs are crafted with zinc blocks by default, meaning the stairs inherit the texture as there is no seperate texture for them

**Comment by Breadabix** [comment]
@MJRLegends Have you seen my posts? The issue still persists in the latest version of ExtraPlanets for 1.7.10.

**Comment by MJRLegends** [comment]
Yeah sorry been busy i will look at this today, update will be out in the next 12 hours :D

**Comment by Breadabix** [comment]
Thanks

**Comment by MJRLegends** [comment]
Sorry for the delay it will be out within the next hour

**Comment by MJRLegends** [comment]
v1.8.4 has been submitted to curse :D

**Comment by Breadabix** [comment]
This has been closed a while but the stairs default crafting recipe still uses zinc blocks, not neptune stone bricks

**Comment by MJRLegends** [comment]
Please make a new issue for it
