### ISSUE TITLE
[1.10.2] Crash Issue

### ISSUE THREAD

**Issue by Bughy2236** [MJRLegends/ExtraPlanets#105]
### Have you checked Closed Issues (if applicable):Yes
Crashes whenever load any dimension (Including Galacticraft ones ex. The moon and Mars)

### Crash Report:
https://pastebin.com/Pk0yUvjn

Version: [1.10.2]

### Additional Information
[Only other mod I am using besides GC an Extra Planets is Mr.Crawfish's Furniture Mod]

**Comment by MJRLegends** [comment]
@Bughy2236 This is a GC bug, i will report it to them

**Comment by MJRLegends** [comment]
@Bughy2236 Which planet was you trying to go to, like the name of it?

**Comment by MJRLegends** [comment]
ping @radfast @micdoodle

**Comment by MJRLegends** [comment]
Note for @radfast and micdoodle8: All my planets that have dungeons are set to 800 and my planets and moons that dont have dungeons are set to 0. im guessing this is fixed by commit https://github.com/micdoodle8/Galacticraft/commit/6739f8747cc600cb1eca12afed1155b1839e5d0f ?

**Comment by radfast** [comment]
@MJRLegends this is #2763 and yes should be fixed by that commit

I just need to get everything else recent merged to 1.10.2 and 1.11.2 and then we will push out Galacticraft build 101

**Comment by MJRLegends** [comment]
@radfast Nice :D thanks cc @Bughy2236

**Comment by Bughy2236** [comment]
The planet I was trying to reach was Ceres, and another thing I should have mentioned is that I had just installed the most recent version of GC and was playing on a world that I had previously used the beta version on

**Comment by MJRLegends** [comment]
@Bughy2236 Yeah, there will be a new Galacticraft version out soon which will be build 101 which will fix this issue for you :D

**Comment by Bughy2236** [comment]
Alright thanks guys :D

**Comment by MJRLegends** [comment]
@radfast Did you see that some builds failed on Jenkins? e.g 1.10 and 1.10 dev and 1.8

**Comment by radfast** [comment]
The crash reported by @Bughy2236 is now fixed - please use latest builds from the download site, that's build 102 for Minecraft 1.10.2.

@MJRLegends  I've been having a few difficulties with Jenkins today, that's for sure.  Could be it's some kind of hangover from the site certificates issue yesterday, anyhow, it's been able to make builds 102 for MC1.8 and 1.10, and 101 at least for 1.11.  The download site has correctly picked up all of these.  We can do any further tidying up over the next few days.

**Comment by MJRLegends** [comment]
@radfast Great thanks, yeah i wanted to make sure you did know of the failed builds before the bug reports flowing in saying the bug is still happening :D

**Comment by radfast** [comment]
The failed builds certainly delayed me getting a proper fix out for the issue in this thread.  But don't worry, the builds which are now available all contain the fix.

That makes two pieces of bad luck we've had on our Galacticraft 4 launch weekend, with the certificates issue and now this!  Hopefully everything should be good from now on.

**Comment by MJRLegends** [comment]
@radfast Yeah, Better late than never so good work... :D

**Comment by radfast** [comment]
@MJRLegends  the key thing now is to spread the message to all the people who've downloaded build 100 that they really need to update.   I know people don't like to update their mods all the time but this one is important, we don't want crashes on space stations and your dungeon-less planets.  If possible can you set your mod to require GC version 4.0.0.101 or later?

(And updating to build 102 also adds Evolved Endermen on Mars and Asteroids dimensions, which are looking good...)

**Comment by MJRLegends** [comment]
@radfast Yeah i might add a detection of GC version like i did for 1.7.10 here to take away the bugs reports from people are using my addon :P https://github.com/MJRLegends/ExtraPlanets/blob/master/src/main/java/com/mjr/extraplanets/handlers/GalacticraftVersionChecker.java

**Comment by radfast** [comment]
An easy one for build 102, see if class galacticraft.core.entities.EntityEvolvedEnderman is present.

Galacticraft doesn't hold the build number in Java, that's because the build number is generated externally by the Jenkins, and additionally because if you are building directly from the Galacticraft sources in your IDE, there won't even **be** a build number.

We do aim to update the minor version number for important updates and then you can detect that (it's in the Constants class). I guess we'll probably update from 4.0.0 to 4.0.1 some time soon.

**Comment by MJRLegends** [comment]
Yeah, i will check for "galacticraft.core.entities.EntityEvolvedEnderman", it will save us the headache of bug reports :D

**Comment by MJRLegends** [comment]
@radfast Also while we are talking here any chance you can change the "Galacticraft3-dev" project on jenkins to Galacticraft "Galacticraft-1.7-dev" please because it kills my OCD haha

**Comment by radfast** [comment]
Not gonna change Jenkins project names, sorry.  I don't know what else on the web might be pointing to that Jenkins project and would break if we were to change it now.

To sooth your OCD, there's definitely a big difference between Galacticraft 3 and Galacticraft 4.   But because Galacticraft 4 is a simultaneous release across three different Minecraft versions, we couldn't just name the Jenkins Galacticraft4, we had to create separate projects for each.

**Comment by MJRLegends** [comment]
@radfast Haha no problem :D

**Comment by MJRLegends** [comment]
@radfast Any chance you could post me a download for dev builds for 101/102 please (only if you have them though) as jenkins is being derpy on them still
