### ISSUE TITLE
[1.8+] Config Typo + Disabling Pressure Doesn't Work

### ISSUE THREAD

**Issue by Truhard** [MJRLegends/ExtraPlanets#309]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes]

### Description of Issue
There is a typo in the ExtraPlanets config related to disabling pressure and radiation on Galacticraft Planets. Also, disabling pressure on all planets and/or disabling radiation on GC planets does not disable pressure on any planets; disabling radiation on GC planets, however, works normally.

### Steps to Reproduce Issue
1. Edit ExtraPlanets config to disable pressure entirely, disable pressure on GC planets.
2. Launch Minecraft.
3. Go to the Moon, Mars, Mercury, Jupiter, etc. without pressure protection.
4. Prepare to die a painful death.

**Crash log/Log (if applicable):** (This is a snip from the config with the typo. Read lines 5 and 6, then read lines 11 and 12) https://pastebin.com/Bb98GZpZ

**Screenshots (if applicable):** 

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [ExtraPlanets-1.12.2-0.3.6, MJRLegendsLib-1.12.2-1.1.3]

**Where did this bug happen:** [Single Player or Server]
Both in singleplayer on multiple clients from different people and on multiplayer server.
### Additional Information
PlanetProgression is installed, however removing it still causes this issue to persist.

**Comment by MJRLegends** [comment]
Updated are rolling out as we speak all should be fixed let me know if theres anymore issues

**Comment by Truhard** [comment]
This bug still exists on multiplayer servers. I've disabled pressure outright, and it is still enabled. I think radiation is aswell? I couldn't tell. All I know is that on singleplayer, this issue is fixed; on multiplayer, the pressure issue still exists.

**Comment by MJRLegends** [comment]
Are you changing you server config to disable the pressure? @Truhard

**Comment by Truhard** [comment]
Yes. In the config, pressure is false and pressure on GC planets is disabled, but it is enabled still.

**Comment by Truhard** [comment]
I've changed both config's settings, singleplayer and multiplayer. The pressure bar does not appear when on the server, but I still take damage without the space suit on.

**Comment by Truhard** [comment]
Yes. My oxygen setup is valid and I'm wearing the correct thermal gear. I've tested this on Mars and Mercury; both planets have pressure enabled, even though the config says otherwise.

**Comment by MJRLegends** [comment]
I will take a look

**Comment by MJRLegends** [comment]
Confirmed to be solved via discord voice chat

**Comment by cestofmir** [comment]
@MJRLegends I am running the latest version of GC and ExtraPlanets and I appear to be having the exact same issue.

**Comment by SebaSphere** [comment]
The server I co-own is having this same issue :I

**Comment by SebaSphere** [comment]
Minecraft Version 1.12.2 - 14.23.4.2705

**Comment by MJRLegends** [comment]
Please make a new issues wish details from your setup/server
